language: java
jdk:
- oraclejdk8
env:
   global:
    - MAVEN_OPTS="-Dmaven.artifact.threads=64"
before_cache:
  - rm -Rf $HOME/.m2/repository/org/talend/sdk/component/components-sample
  - rm -Rf $HOME/.m2/repository/org/talend/components
cache:
  directories:
  - "$HOME/.m2"
script: mvn clean install
